version: "3.8"
services:
  song-service:
    build:
      context: ./song-service
      dockerfile: Dockerfile
    depends_on:
      song-db:
        condition: service_healthy
    ports:
      - 8081:8081
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://song-db:5433/postgres
        SERVER_PORT: 8081
  resourceservice:
    build:
      context: ./resourceservice
      dockerfile: Dockerfile
    depends_on:
      resource-db:
        condition: service_healthy
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://resource-db:5432/postgres
        SERVER_PORT: 8080
        SPRING_APPLICATION_JSON: '{
                 "spring": {
                     "servlet": {
                         "multipart": {
                             "max-file-size": "20MB",
                             "max-request-size": "20MB"
                         }
                     }
                 },
                 "songservice.baseAddress": "http://song-service:8081"
             }'

  song-db:
    image: postgres
    ports:
      - 5433:5433
    environment:
      POSTGRES_PASSWORD: password
      PGPORT: 5433
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3
  resource-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3
