version: "3.8"
services:

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    env_file:
      - ./eureka-server/.env
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - mynetwork
    hostname: eureka-server
  song-service-1:
    build:
      context: ./song-service
      dockerfile: Dockerfile
    depends_on:
    - song-db
    - eureka-server
    ports:
      - 8081:8081
    env_file:
      - ./song-service/.env
    networks:
      - mynetwork
    links:
    - "eureka-server"

  song-service-2:
    build:
      context: ./song-service
      dockerfile: Dockerfile
    depends_on:
    - song-db
    - eureka-server
    ports:
      - 8082:8081
    env_file:
      - ./song-service/.env
    networks:
      - mynetwork
    links:
    - "eureka-server"
   
  resourceservice:
    build:
      context: ./resourceservice
      dockerfile: Dockerfile
    depends_on:
      - resource-db
      - eureka-server
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 512M
    env_file:
      - ./resourceservice/.env
    networks:
      - mynetwork
    links:
    - "eureka-server"
    

  song-db:
    image: postgres:alpine
    ports:
      - 5433:5433
    environment:
      POSTGRES_PASSWORD: password
      PGPORT: 5433
    volumes:
        - ./init-db/init-song.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - mynetwork
  resource-db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./init-db/init-resource.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - mynetwork

networks:
  mynetwork: {}
