version: "3.8"
services:
  song-service:
    build:
      context: ./song-service
      dockerfile: Dockerfile
    depends_on:
      song-db:
        condition: service_healthy
    ports:
      - 8081:8081
    env_file:
      - ./song-service/.env
  resourceservice:
    build:
      context: ./resourceservice
      dockerfile: Dockerfile
    depends_on:
      resource-db:
        condition: service_healthy
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 512M
    env_file:
      - ./resourceservice/.env

  song-db:
    image: postgres:alpine
    ports:
      - 5433:5433
    environment:
      POSTGRES_PASSWORD: password
      PGPORT: 5433
    volumes:
        - ./init-db/init-song.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3
  resource-db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./init-db/init-resource.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3
